version: '3.9'

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8080:8000"
    environment:
      MONGO_URL: mongodb://mongo:20069
    volumes:
      - ./:/app/host_mount  # Mount host's ./logs directory to /app/logs in container
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: mongodb
    command: mongod --port 20069
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: