version: '3.9'

services:
  web:
    build: .
    container_name: fastapi_app
    ports:
      - "8080:8000"
    environment:
      MONGO_URL: mongodb://mongo:27017
      SECRET_KEY: ${SECRET_KEY:-fallback_dev_key_only_set_in_env}
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: